# Assignment1

In [2]:
import numpy as np

# Question1

In [16]:
a=np.arange(1,11)
print(a)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.shape)
print(a.data)

[ 1  2  3  4  5  6  7  8  9 10]
1
int32
10
(10,)


In [17]:
b=np.arange(1,10).reshape(3,3)
print(b)
print(b.ndim)
print(b.dtype)
print(b.size)
print(b.shape)
print(b.data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
int32
9
(3, 3)


In [18]:
c=np.arange(1,28).reshape(3,3,3)
print(c)
print(c.ndim)
print(c.dtype)
print(c.size)
print(c.shape)
print(c.data)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3
int32
27
(3, 3, 3)


In [20]:
print("="*75)

# Question 2

In [22]:
b=np.arange(1,16).reshape(3,5)
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [27]:
b=np.empty((3,5))
print(b)


[[4.67296746e-307 1.69121096e-306 1.29061074e-306 8.34441742e-308
  1.78022342e-306]
 [6.23058028e-307 9.79107872e-307 6.89807188e-307 7.56594375e-307
  6.23060065e-307]
 [1.78021527e-306 8.34454050e-308 1.11261027e-306 2.04712907e-306
  3.49698923e-317]]


In [29]:
a=np.full((3,5),2)
print(a)


[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [36]:
a=np.zeros((3,5),dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [39]:
a=np.ones((3,5),dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
print("="*75)

# Question 3

In [41]:
d=np.arange(14,41)
print(d)

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37
 38 39 40]


In [42]:
print(d.reshape(3,9))

[[14 15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40]]


In [44]:
print("="*75)


# Question 4

In [3]:
a=np.arange(1,41).reshape(8,5)
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [4]:
print("="*75)

# Question 5,6

In [7]:
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [19]:
a.resize(4,10)
print(a)

ValueError: resize only works on single-segment arrays

In [12]:
e=a[0:3,0:4]
print(e)

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


In [16]:

print(a)

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


In [20]:
a=np.arange(1,41).reshape(8,5)
a.resize(4,10)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [24]:

g=a[0:4,4]
print(g)

[ 5 15 25 35]


In [25]:
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [26]:
h=a[2:]
print(h)

[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [27]:
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [29]:
i=a[:,2:5]
print(i)

[[ 3  4  5]
 [13 14 15]
 [23 24 25]
 [33 34 35]]


In [30]:
print("="*75)

# Question7

In [31]:
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [34]:
j=a[a%2==1]
print(j)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [35]:
print("="*75)

# Question8

In [36]:
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [48]:
a[a%2==0]=-1
print(a)

[[ 1 -1  3 -1  5 -1  7 -1  9 -1]
 [11 -1 13 -1 15 -1 17 -1 19 -1]
 [21 -1 23 -1 25 -1 27 -1 29 -1]
 [31 -1 33 -1 35 -1 37 -1 39 -1]]


In [49]:
print(a)


[[ 1 -1  3 -1  5 -1  7 -1  9 -1]
 [11 -1 13 -1 15 -1 17 -1 19 -1]
 [21 -1 23 -1 25 -1 27 -1 29 -1]
 [31 -1 33 -1 35 -1 37 -1 39 -1]]


In [52]:
print("="*75)

# Question9

In [50]:
m=np.arange(1,11)
n=np.arange(11,21)
print(m)
print(n)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [51]:
a1=np.append(m,n)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [53]:
print("="*75)

# Question10

In [57]:
a2=np.arange(1,17).reshape(2,8)
print(a2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [58]:
print("="*75)

# Question11

In [59]:
a3=np.random.randint(13,40,12)
print(a3)

[19 34 19 28 31 26 27 18 30 21 35 31]


In [60]:
a4=np.sort(a3)
print(a4)                                      #ascending order

[18 19 19 21 26 27 28 30 31 31 34 35]


In [61]:
a5=a4[: :-1]                                     #descending order
print(a5)

[35 34 31 31 30 28 27 26 21 19 19 18]


In [63]:
print("="*75)

# Question12

In [77]:
g=np.arange(1,16).reshape(5,3)
print(g)
print("="*75)
print(g+4)                 #addition
print("="*75)
print(g*2)                 #multiplication
print("="*75)
print(g-3)                 #subtraction
print("="*75)
print(g/2)                #divison

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]
 [26 28 30]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]
 [5.  5.5 6. ]
 [6.5 7.  7.5]]


In [78]:
print("="*75)
print("="*75)

# Question13

In [80]:
m=np.arange(1,10).reshape(3,3)
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
v=np.arange(1,10).reshape(3,3)
print(v)
c=m+v
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [85]:
d=m*v
print(d)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [87]:
s=m-v
print(s)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [90]:
y=m.dot(v)
print(m)
print(v)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [92]:
d=m/v
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [95]:
print(y.sum())
print(y.min())
print(y.max())

729
30
150


In [104]:
print(y.sum(axis=0))
print(y.min(axis=0))
print(y.max(axis=0))
            

[198 243 288]
[30 36 42]
[102 126 150]


In [105]:
print(y.sum(axis=1))
print(y.min(axis=1))
print(y.max(axis=1))

[108 243 378]
[ 30  66 102]
[ 42  96 150]
